version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file package.yaml
artifacts:
  files:
   - template.yaml
   - package.yaml
