version: 0.2
phases:
 build:
   commands:
     - aws cloudformation package
     --template-file template.yaml
     --s3-bucket $S3_BUCKET
     --output-template-file package.yaml
artifacts:
 type: zip
 files:
   - template.yaml
   - package.yaml