AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-python-function
Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Handler: temp.lambda_handler

Parameters:
  User:
    Type: String
    Default: Dev
  Region:
    Type: String
    Default: ap-south-1
  AWSEnv:
    Type: String
    Default: Dev
  APIStage:
    Type: String
    Default: stage


Resources:

  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "tahmarketplace-api"
      StageName: Stage


  # Layer:
  #   Type: 'AWS::Serverless::LayerVersion'
  #   Properties:
  #     LayerName: bs4-python36
  #     Description: Beautiful Soup 4 Layer for Python 3.6
  #     ContentUri: ./Layers
  #     CompatibleRuntimes:
  #       - python3.6
  #     RetentionPolicy: Retain
  #   Metadata:
  #     BuildMethod: python3.9 | makefile

  CreateActivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions
      Handler: app.lambda_handler
      MemorySize: 1024
      # Layers: !Ref bs4Layer
      # Role: arn:asd3434234234
      Environment:
        Variables:
          TABLE: !Ref Table
          REGION: !Ref Region
          AWSENV: !Ref AWSEnv
      Events:
        TAHApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: ANY
            RestApiId:
              Ref: BasicAWSApiGateway

Outputs:
  BasicAWSApiGateway:
    Description: 'API Gateway endpoint URL for Staging stage for Hello World function'
    Value: !Sub 'https://${BasicAWSApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/hello/'
  BasicAWSApiGatewayRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref BasicAWSApiGateway
    Export:
      Name: BasicAWSApiGateway-RestApiId
  BasicAWSApiGatewayRootResourceId:
    Value: !GetAtt BasicAWSApiGateway.RootResourceId
    Export:
      Name: BasicAWSApiGateway-RootResourceId