AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-python-function
Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Handler: temp.lambda_handler

Parameters:
  User:
    Type: String
    Default: Dev
  Region:
    Type: String
    Default: us-east-2
  AWSEnv:
    Type: String
    Default: Dev
  APIStage:
    Type: String
    Default: stage


Resources:

  TAHApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "tahmarketplace-api"
      StageName: !Ref APIStage
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*' # allows for logging on any resource
          HttpMethod: '*' # allows for logging on any method
      TracingEnabled: true
      Variables:
        LAMBDA_ALIAS: !Ref Stage
        
  Layer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: bs4-python36
      Description: Beautiful Soup 4 Layer for Python 3.6
      ContentUri: ./Layers
      CompatibleRuntimes:
        - python3.6
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.9 | makefile

  CreateActivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hello-world
      Handler: temp.lambda_handler
      MemorySize: 1024
      Layers: !Ref bs4Layer
      Environment:
        Variables:
          TABLE: !Ref Table
          REGION: !Ref Region
          AWSENV: !Ref AWSEnv
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get