name: Deploy image to ECSS
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
        - stage
        - devp

      imageTag: 
        description: 'Squire backend image tag to deploy'
        required: true
        default: 'latest' 
        type: string

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: registry.hub.docker.com
  ECS_SERVICE: httpd
  ECS_CLUSTER: stage-test
  ECS_TASK_DEFINITION: ./task-definitions.json
  CONTAINER_NAME: httpd

jobs:
    deploy:
      runs-on: ubuntu-latest
      name: Deploy

      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Chosen image tag
          run: echo ${{ github.event.inputs.imageTag }}

        - name: Login to ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
        
        - name: Fill in the new image ID in the Amazon ECS task definition
          id: task-def
          uses: aws-actions/amazon-ecs-render-task-definition@v1
          with:
            task-definition: ${{ env.ECS_TASK_DEFINITION }}
            container-name: ${{ env.CONTAINER_NAME }}
            image: ${{ github.event.inputs.imageTag }}
        
        - name: Deploy Amazon ECS task definition
          uses: aws-actions/amazon-ecs-deploy-task-definition@v1
          with:
            task-definition: ${{ steps.task-def.outputs.task-definition }}
            service: ${{ env.ECS_SERVICE }}
            cluster: ${{ env.ECS_CLUSTER }}
            wait-for-service-stability: true

        - name: Send slack notification on failure
          if:  ${{ failure() }}
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_BACKEND }}
            SLACK_COLOR: ${{ job.status }}
            MSG_MINIMAL: actions url
            SLACK_TITLE: "Backend Deployment Status"
            SLACK_MESSAGE: ':bangbang: Backend deployment *FAILED* with image tag:* ${{ github.event.inputs.imageTag }}* in environment:* ${{ github.event.inputs.env }}*  :bangbang:*' 
     
